# Generated by Django 3.2.24 on 2024-03-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(),
        ),
    ]
