# Generated by Django 3.2.24 on 2024-04-01 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0006_task_credited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_name', models.TextField()),
                ('description', models.TextField()),
                ('stock', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('team_name', models.TextField()),
                ('members', models.ManyToManyField(to='myapp430.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('team_id', models.IntegerField(null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp430.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('deadline', models.DateTimeField()),
                ('points', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('In Progress', 'In Progress')], default='In Progress', max_length=11)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp430.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_name', models.TextField()),
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('location', models.TextField()),
                ('participants', models.ManyToManyField(blank=True, to='myapp430.Employee')),
            ],
        ),
    ]
