# Generated by Django 3.2.24 on 2024-04-02 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0007_events_gifts_goals_mood_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='participants',
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp430.events')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp430.employee')),
            ],
            options={
                'unique_together': {('event', 'participant')},
            },
        ),
    ]
