# Generated by Django 3.2.24 on 2024-04-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0008_auto_20240402_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='employee',
        ),
        migrations.AddField(
            model_name='task',
            name='employees',
            field=models.ManyToManyField(to='myapp430.Employee'),
        ),
    ]
