# Generated by Django 3.2.24 on 2024-04-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0011_alter_task_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='employees',
            field=models.ManyToManyField(blank=True, to='myapp430.Employee'),
        ),
    ]
