# Generated by Django 4.2.10 on 2024-04-15 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp430", "0012_alter_task_employees"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mood",
            name="mood",
            field=models.CharField(
                choices=[
                    ("Awful", "Awful"),
                    ("Bad", "Bad"),
                    ("Neutral", "Neutral"),
                    ("Good", "Good"),
                    ("Amazing", "Amazing"),
                ],
                max_length=20,
            ),
        ),
    ]
