# Generated by Django 3.2.24 on 2024-04-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0018_auto_20240418_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
