# Generated by Django 3.2.24 on 2024-04-18 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0017_auto_20240417_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_name', models.TextField()),
                ('description', models.TextField()),
                ('stock', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Gifts',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='points',
        ),
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
