# Generated by Django 3.2.24 on 2024-04-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0020_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
