# Generated by Django 3.2.24 on 2024-03-27 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0002_auto_20240327_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp430.employee'),
        ),
    ]
