# Generated by Django 3.2.24 on 2024-03-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0004_auto_20240327_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('In Progress', 'In Progress')], default='In Progress', max_length=11),
        ),
    ]
