# Generated by Django 3.2.24 on 2024-03-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='credited',
            field=models.BooleanField(default=False),
        ),
    ]
